// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// make_real_altrep
SEXP make_real_altrep(size_t n);
RcppExport SEXP _testPkg_make_real_altrep(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(make_real_altrep(n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_testPkg_make_real_altrep", (DL_FUNC) &_testPkg_make_real_altrep, 1},
    {NULL, NULL, 0}
};

void ini_altrep_real_class(DllInfo *dll);
RcppExport void R_init_testPkg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    ini_altrep_real_class(dll);
}
