# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_real_altrep <- function(n) {
    .Call(`_testPkg_make_real_altrep`, n)
}

make_integer_altrep <- function(n) {
    .Call(`_testPkg_make_integer_altrep`, n)
}

